### ISSUE TITLE
no-multi-spaces usage

### ISSUE THREAD

**Issue by jmlopez-rod** [buzinas/tslint-eslint-rules#102]
Hi, I'm trying to write the rule for no-multi-spaces and I was just wondering about the documentation: 

```
"no-multi-spaces": [
    true,
    {
      "exceptions": [ { "ImportDeclation": true }, { "Property": false } ]
    }
  ]
```

Why are we making the exceptions a list of objects with only a single key? wouldn't it be easier to remember its usage if we just think of the exceptions as an object where you can turn the rule off and on?

```
"no-multi-spaces": [
    true,
    {
      "exceptions": {
        "ImportDeclaration": true,
        "Property": false
      }
    }
  ]
```

Either way, I still have yet to write the rule but I will keep this issue open to talk about its progress.

**Comment by jmlopez-rod** [comment]
I have succeed in creating the rule and the eslint tests are passing. I have also opted to use my suggestion on how to provide the exceptions. I will create a pull request as soon as the other PRs I have submitted get resolved. For anyone interested see this diff:

https://github.com/jmlopez-rod/tslint-eslint-rules/compare/object-curly-spacing...jmlopez-rod:no-multi-spaces

**Comment by buzinas** [comment]
Not sure why it was a list of objects, probably a typo.

I'll be glad to accept the PR.
