### ISSUE TITLE
enforcing object-curly-brace in project

### ISSUE THREAD

**Issue by jmlopez-rod** [buzinas/tslint-eslint-rules#105]
So far it seems that the project is following the rule of adding a space in the braces:

```
const obj = { key: value };
```

But on the imports we are doing

```
import {foo} from 'bar';
```

Once the `object-curly-brace` is added we should enforce it so that we either always have a space or not. Any thoughts?

**Comment by buzinas** [comment]
I'll fix that for the next release. Thanks for the issue!
