### ISSUE TITLE
condensed rule list

### ISSUE THREAD

**Issue by jmlopez-rod** [buzinas/tslint-eslint-rules#107]
As it currently stands, the README file has grown a lot and it gets harder to see the available rules. I'd like to suggest the following:

Create a wiki page for each rule that is created in the project and create a table in the readme file which provides the links to the orginal eslint docs, tslint docs and the wiki page for the rule.

The table may be in the following form:

| Availability | eslint | tslint | description  |
| :---         |     :---:      |          :---: | :--- | ---:|
| ☑️ | [comma-dangle][1] | [trailing-comma][11] | disallow or enforce trailing commas  | 
| ❌ | [no-extra-parens][2] | no-extra-parens |  disallow unnecessary parentheses |
| ✅ | [no-duplicate-case][3] | [no-duplicate-case][33] | disallow a duplicate case label |

[1]: http://eslint.org/docs/rules/comma-dangle
[11]: http://palantir.github.io/tslint/rules/trailing-comma/
[2]: http://eslint.org/docs/rules/no-extra-parens
[3]: http://eslint.org/docs/rules/no-duplicate-case
[33]: #link-to-wiki-page

Here the ☑️  denotes that it is a available natively while the ✅ denotes that the rule is available through tslint-eslint. The big ❌ tells that we need to work on it (replaces the TODO string)

I have already played around creating this table in another branch a bit and I was wondering if this addition would be welcomed before I create a proper pull request.

**Comment by buzinas** [comment]
I would be glad to accept a PR for this :)

**Comment by jmlopez-rod** [comment]
Ok, still working on this, I'll make a PR for this but it needs more work and discussion. Here you can see a preview of the full table: https://github.com/jmlopez-rod/tslint-eslint-rules/tree/readme-rules-table
