### ISSUE TITLE
no-multi-spaces not apart of dist/rules

### ISSUE THREAD

**Issue by zelein** [buzinas/tslint-eslint-rules#113]
I installed tslint-eslint-rules and TSLint is complaining about not recognizing the no-multi-spaces rule. I checked in `node_modules/tslint-eslint-rules/dist/rules` and the `noMultiSpacesRule.js` is non-existent.

**Comment by buzinas** [comment]
It was added in #106, but no releases were made since them. I'll publish 1.6 soon.

**Comment by buzinas** [comment]
@zelein v1.6.0 released
