### ISSUE TITLE
Update project to support TSLint extends

### ISSUE THREAD

**Issue by zelein** [buzinas/tslint-eslint-rules#115]
TSLint now supports the `extends` property like ESLint.

tslint-eslint-rules should be updated to export its rules with the default set to take advantage of module resolution so that we no longer have to specify the rules directory. Then the developer using the config can just turn off or change what they need as normal in the "rules" property.

**Comment by buzinas** [comment]
It's not in the project's scope, but I'll be glad to accept a PR for this.

**Comment by zelein** [comment]
Understandable. The problem I'm having is I am wrapping this config within my own config, but when I install it in another project the path resolution to the rulesDirectory is no longer correct. This is because NPM is installing the tslint-eslint-rules module at the top level node_modules instead of within my wrapped config module.

**Comment by jmlopez-rod** [comment]
I'm not sure if that would be a good idea. As @buzinas mentioned, the scope of the project is to provide rules, it is up to users to choose what they need from it. As an example take a look at this project: https://github.com/blakeembrey/tslint-config-standard, this one creates a configuration using the rules provided by the project.

**Comment by zelein** [comment]
Thanks for the insight. That has indirectly led me to what I think will solve my issue.

`rulesDirectory: path.join(path.dirname(require.resolve('tslint-eslint-rules')), 'dist/rules'),`

**Comment by buzinas** [comment]
Thanks @jmlopez-rod. If it doesn't solve your issue, feel free to share your code/project, and I can try to help you. If it does, then feel free to close the issue :)

**Comment by zelein** [comment]
The bit of code I provided above proved successful!

Thanks all.
