### ISSUE TITLE
upgrading to typescript 2.0

### ISSUE THREAD

**Issue by jmlopez-rod** [buzinas/tslint-eslint-rules#116]
Now that typescript 2.0 is out we may want to update our dependencies and check that everything works well with TSLint. Also, we may be able to get rid of the `typings` folder since we will be able to do `npm install @types/[insert-package-here]` and typescript should be able to pick up the definitions.

**Comment by buzinas** [comment]
Although v2.0 was published, since the main package is still 1.8.10 (when doing `npm i typescript`, it installs 1.8.10 yet), I'll wait for 2.0 being replacing it as the main one.

**Comment by jcristovao** [comment]
Hey @buzinas , are you sure? Because looking at [npm](https://www.npmjs.com/package/typescript) now the current version seems to be 2.0.3

**Comment by buzinas** [comment]
At the time I was writing, yeah, I'm sure. But I didn't test it today, so I don't know if it's no longer true. I'm completely busy today, but I'll check this later, when I got sometime.

**Comment by jcristovao** [comment]
Sure! I was just commenting because I was doing the upgrade today and I noticed it was official, so I had that fresh on my mind :)

**Comment by jcristovao** [comment]
Thanks!
