### ISSUE TITLE
Review `handle-callback-err` rule

### ISSUE THREAD

**Issue by blakeembrey** [buzinas/tslint-eslint-rules#120]
I enabled it briefly, but it's still a bit buggy (unfortunately). I'm logging this issue to make sure I or someone else can review later. Here's the latest location that failed and I believe should have passed:

* https://github.com/blakeembrey/compose-middleware/blob/master/src/index.ts#L61-L79

**Comment by blakeembrey** [comment]
Oh, I remember the other issue I encountered - all the TSLint indexes were off-by-one.

**Comment by blakeembrey** [comment]
Oh, that's interesting - it seems that it is passing, but fails when the error argument is not in the first position. Investigating now, hopefully I'll have a PR for you 😄 Any advice on test the position?

**Comment by buzinas** [comment]
Didn't understand exactly what you meant.

**Comment by blakeembrey** [comment]
Sorry, I wanted to add a test and make sure the off-by-one error didn't appear again. It's all good though, I've just implemented it like I saw other code and it should work fine now. PR inbound!
