### ISSUE TITLE
Please generate and publish as ES5

### ISSUE THREAD

**Issue by blakeembrey** [buzinas/tslint-eslint-rules#124]
This project has broken on every node version except 6.0 since the 2.0 release - can you please transpile it to ES5 instead of ES6? See https://travis-ci.org/TypeStrong/ts-node/builds/164519486.

**Comment by buzinas** [comment]
Yeah, you're right. That's exactly why it was a major bump instead of a minor one.

It was [a breaking change for dropping support on older Node versions](https://github.com/buzinas/tslint-eslint-rules/commit/a8f558f8b25ec0965c1d31bac5ed603713f569f6#diff-354f30a63fb0907d4ad57269548329e3).

**Comment by blakeembrey** [comment]
But why? There's literally no reason to do this, and as a result I'll end up just forking the entire project and working by myself instead because I can't recommend this to anyone anymore. I'd love not to duplicate efforts and I see zero reason why'd you change this - it's not like it changes development for you either, since you're using TypeScript as a transpiler.

**Comment by blakeembrey** [comment]
For reference, every single project I develop is currently broken. That's around 100 projects for me alone. It's pretty ridiculous to impose a min-node version on a development tool like linting. If you don't want to support older node versions (which, by the way, are currently being used in production still - not everyone runs on the cutting edge, 4.0 is still LTS) I'll be happy to maintain a fork instead.

**Comment by blakeembrey** [comment]
I can also rely on 1.0 as you suggest, but you aren't developing the 1.0 branch anymore and it still contains all those bugs I just fixed. If you are maintaining 1.0, please open a branch so I can make PRs against that instead to maintain it.

**Comment by jmlopez-rod** [comment]
I'm with @blakeembrey on this one. Not everyone is yet using node 6.0, in some cases I have found myself going back to node v5 simply because node 6 breaks some of my projects. Can we get transpilation to es5 pretty please?

**Comment by buzinas** [comment]
OK, you have fair concerns. I'll accept a PR for changing the compilation target to ES5.

**Comment by buzinas** [comment]
Please, while targeting ES5, some contributors started using `Map` and `Promise`. None of them are available in ES5, so you'll need to add type definitions for them.

**Comment by jmlopez-rod** [comment]
@buzinas , `Promise` and `Map` seems to be included in `node_modules/typescript/lib/lib.es6.d.ts` which is included in the build process as a source file. Perhaps we can change to es6 once the TSLint project changes to it: https://github.com/palantir/tslint/blob/master/scripts/tsconfig.json

**Comment by buzinas** [comment]
If we're referencing it, we must do it inside `tslint.json` instead of one of the parameters to `gulp-tslint`.

**Comment by blakeembrey** [comment]
Can I replace `Map` and `Promise` with ES5 equivalents? I couldn't find where `Promise` is used, and fixing the `Map` usage is also pretty straightforward since it's only used as a dictionary anyway.

**Comment by jmlopez-rod** [comment]
@blakeembrey Promises are used in `src/readme` to deal with reading files asynchronously.

**Comment by buzinas** [comment]
@blakeembrey for me, absolutely no problems in replacing them.

**Comment by blakeembrey** [comment]
@jmlopez-rod Is that only for generation and not runtime? I'd be fine not touching that then.

**Comment by jmlopez-rod** [comment]
@blakeembrey , yeah, those are only for generating the readme file contents, they are not used within the rules. Either way, saw the PR, it looks good. I was going to add it but I did not feel so comfortable adding another `.d.ts` file. With TS 2.0 many projects include their definitions so this looks really good.
