### ISSUE TITLE
project rule prefix

### ISSUE THREAD

**Issue by jmlopez-rod** [buzinas/tslint-eslint-rules#129]
In the tslint [docs](https://palantir.github.io/tslint/develop/custom-rules/) it states

> Core rules cannot be overwritten with a custom implementation.

What would happen when tslint creates a core rule that has the same name as one provided by eslint? Will our rule become invalid and we won't be able to use it? As of now I'm almost ready to submit a PR for the `indent` rule, but this rule is already a core rule for tslint. I know in the issue you suggested we name it `indent-size` but this would only solve the issue with the rule.

Would you be open to the idea of naming future rules with the prefix `ter` (teslint-eslint-rules)? For instance `ter-indent`.  Or just `eslint-indent` since the rule is a port from eslint. In this way for future rules that tslint comes up with when we use the rule we know it comes from this project.

Again, the main reason I bring this up is because of future name clashing.

**Comment by buzinas** [comment]
This is a breaking change, not sure if the problems caused by different implementations would be relevant enough to do this.

I'll leave the issue open, so we can see how the community react, and also maybe someone comes with a great idea. Let's see what happens. For now, let's wait :)

**Comment by jmlopez-rod** [comment]
It is a breaking change, that's why we are not going to go and rename all the rules we have right now. I think the rules that are standing right now we'll stay as they are, and only in the case TSLint provides a core rule with the same name then we change the name so that users can select between the core rule or the one provided by the project. At that point we simply deprecate the rule in favor of the one with the new name.

I'm bringing this up because I rather not just give a name to the indent rule different from what ESLint has named it. Either way, there are some rules which are "safe" to name, for instance `max-line` since they have named it `max-line-length`. I have a PR to make it more like the rule in eslint but the [PR](https://github.com/palantir/tslint/pull/1548) is just sitting there.

At this point I'd rather just bring it here under the name `ter-max-line`.

**Comment by jmlopez-rod** [comment]
But yeah, lets wait to see what others have to say. I think people would find it easier to just see the prefix and know where the rule comes from.

**Comment by buzinas** [comment]
Well, I think that - for now - we can use the `ter` prefix only for the rules that already cause conflicts.
