### ISSUE TITLE
The rule is provided natively by TSLint.

### ISSUE THREAD

**Issue by Diokuz** [buzinas/tslint-eslint-rules#134]
What exactly does that mean?

1. The rule is provided by tslint, but you also can use eslint version.
2. The rule is provided by tslint and will never be in `tslint-eslint-rules`. Links to eslint docs are just for information.

for example: `no-trailing-spaces` rule of eslint is in readme (and I thought I can use it, because tslint version `no-trailing-whitespace` is buggy), but it doesnt work at all.

**Comment by jmlopez-rod** [comment]
It really just means that the rule is provided by TSLint at the moment. If the rule provided by TSLint doesn't match what ESlint does then we may write that rule and change the status of the rule to say that this project provides it.

I would say that if a native TSLint rule is buggy we should report it to the TSLint project. But given that their releases take a long time, it is almost better to try to write the rule yourself (or ask nicely if someone else would do it) and submit it here. Only as long as the rule attempts to do everything the eslint rule does.
