### ISSUE TITLE
ter-indent not working properly?

### ISSUE THREAD

**Issue by fxlemire** [buzinas/tslint-eslint-rules#143]
Using the following configuration:
```
"ter-indent": [
  true,
  2,
  {
    "SwitchCase": 1,
    "VariableDeclarator": {"var": 2, "let": 2, "const": 3},
    "outerIIFEBody": 0,
    "MemberExpression": 1,
    "FunctionDeclaration": {"body": 1, "parameters": 2},
    "FunctionExpression": {"body": 1, "parameters": 2},
    "CallExpression": {"arguments": 1}
  }
]
```
I need to format my code as following to avoid the squiggly green lines in VS Code:
```
export class HomePage {
  constructor(
      public navCtrl: NavController,
      public name: string) {
        return this;
      }
}
```
But it should be formatted as following if I'm not mistaken:
```
export class HomePage {
  constructor(
      public navCtrl: NavController,
      public name: string) {
    return this;
  }
}
```
Using versions `"tslint": "^4.0.2", "tslint-eslint-rules": "^3.0.0",`

Also, removing the entire object of configurations does not change anything.

**Comment by jmlopez-rod** [comment]
Sorry, I haven't done a release yet. The documentation is pointing to the latest code which isn't in npm yet. I'll be doing a release sometime tonight which should fix the issue.

**Comment by fxlemire** [comment]
Oh okay thanks!

**Comment by jmlopez-rod** [comment]
@fxlemire I just realized that in a class, a constructor and methods are not FunctionExpressions or declarations (at least in typescript). Does eslint actually handle parameters in them? The call expression option will handle cases like the following:

```
foo(
 a,
   b
c)
```

But not for parameters in class methods. I've been also wanting to make the rule keep indentation especially for classes. I'll have a look, hopefully it won't take much time.

**Comment by fxlemire** [comment]
@jmlopez-rod Awesome. My pleasure, thanks to you for looking into that!

**Comment by jmlopez-rod** [comment]
v3.1.0 has been released. You intended example should work now.
