### ISSUE TITLE
typeof-compare rule in tslint

### ISSUE THREAD

**Issue by ikokostya** [buzinas/tslint-eslint-rules#169]
Table https://github.com/buzinas/tslint-eslint-rules#possible-errors contains [valid-typeof](https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/validTypeofRule.md) rule. Tslint has similar standard rule [typeof-compare](https://palantir.github.io/tslint/rules/typeof-compare/).

**Comment by buzinas** [comment]
Well, since the names don't collide and there is already a similar rule here, I think we don't have a problem with this.
