### ISSUE TITLE
Standard tslint arrow-parens rule

### ISSUE THREAD

**Issue by ikokostya** [buzinas/tslint-eslint-rules#170]
`tslint` has standard [arrow-parens](https://palantir.github.io/tslint/rules/arrow-parens/) rule.

Anyway I like [ter-arrow-parens](https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/terArrowParensRule.md) rule more, because it has similar format with `eslint`.

**Comment by jmlopez-rod** [comment]
Precisely, I wrote the `ter-arrow-parens` to make it the same (or as close as possible) as the the one in eslint. Either way, I did provide a link to the `arrow-parens` in the docs for the rule.

Is there an issue with `ter-arrow-parens`? Do we need to keep this issue open?

**Comment by ikokostya** [comment]
> I did provide a link to the arrow-parens in the docs for the rule.

Sorry, I missed this link.

> Is there an issue with ter-arrow-parens?  Do we need to keep this issue open?

No issues. Closing.
