### ISSUE TITLE
Support fix option for ter-indent

### ISSUE THREAD

**Issue by arloduff** [buzinas/tslint-eslint-rules#185]
Is it possible to support the automatically fixing files for the `ter-indent` rule? Right now, my experience is that tslint is complaining about files that have the wrong number of spaces, but I would like for it to automatically fix the files that have the incorrect number of spaces.

I'm using gulp  together with tslint and tslint-eslint-rules.

### Versions:
gulp-tslint: 7.1.0
tslint: 4.4.2
tslint-eslint-rules: 3.4.0

### tslint.json:

    {
      "extends": [
        "tslint-eslint-rules"
      ],
      "rules": {
        "ter-indent" : [
          true,
          2
        ]
      }
    }

I am specifying the `fix` option in my **gulpfile**:

    var gulp = require('gulp');
    var tslint = require('gulp-tslint');

    gulp.task('default', function () {
      return gulp.src('./**/*.ts')
        .pipe(tslint({
          configuration: 'config/tslint.json',
          fix: true
        }))
        .pipe(tslint.report());
    });

### Example code:

    import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
    import { enableProdMode } from '@angular/core';

    import { AppModule } from './modules/main/app.module';

    import {CommunicationService} from './shared/services/communication/communication.service';

    if (process.env.ENV === 'production') {
           enableProdMode();
      }

    platformBrowserDynamic().bootstrapModule(AppModule,[CommunicationService])

### Expected behavior:;

The if block `if(process.ENV === 'production') {` should be reformatted as:

    if (process.env.ENV === 'production') {
      enableProdMode();
    }

### Actual behavior:

The line is not reformatted, but a warning message appears.

**Comment by jmlopez-rod** [comment]
Currently the ter-indent rule does not have a fixer. Only a few of the rules have it implemented. I'll try to add it on the next update to the rule.

**Comment by arloduff** [comment]
Thanks!
