### ISSUE TITLE
TSLint's ordered-imports does not work like ESLint's sort imports

### ISSUE THREAD

**Issue by MeltingMosaic** [buzinas/tslint-eslint-rules#189]
TSLint's [ordered-imports](https://palantir.github.io/tslint/rules/ordered-imports/) doesn't work at all like ESLint's [sort-imports](http://eslint.org/docs/rules/sort-imports) rule. 

I propose that a new rule be written that works more like ESLint's with respect to the ordering of import types (single, multiple, all, none).

I have written a rule that detects the issues correctly but does not provide a fixer.

**Comment by MeltingMosaic** [comment]
#190 Added PR (Sorry if this isn't the right way to do this - I'm a noob).

**Comment by jmlopez-rod** [comment]
Thanks for the PR. I did a quick review to point you in the right direction on how to format the PR. As far as the fixer goes I would look at the eslint fixer to try to come up with it. I'll try to help you on this one once everything else is taken care of. Thanks again for joining on the fun.
