### ISSUE TITLE
valid-jsdoc: New option to make parameter types optional.

### ISSUE THREAD

**Issue by battmanz** [buzinas/tslint-eslint-rules#191]
In TypeScript, specifying the parameter types in the documentation is really not that helpful. In fact, it's redundant. You can easily see the parameter types by looking at the code. By way of comparison, in Javadoc you don't put any type information in the documentation either, because it's part of the language.

I'm proposing a new option `requireParamType` that if set to false, will not require the parameter types.

**Comment by jmlopez-rod** [comment]
This makes sense. I'll try to include it with the fix for this: https://github.com/buzinas/tslint-eslint-rules/issues/178

**Comment by battmanz** [comment]
Thank you!
