### ISSUE TITLE
Question: How to indent with 2 tabs

### ISSUE THREAD

**Issue by basickarl** [buzinas/tslint-eslint-rules#197]
Does not work:
```
        "indent": [
            "error",
            "tab",
            2
        ],
```
Does not work:
```
        "indent": [
            "error",
            2
        ],
        "indent": [
            "error",
            "tab"
        ],
```

I'd like to decide that indenting is done via tabs and I'd like to decide how many tabs. The documentation does not state if this is possible.

**Comment by buzinas** [comment]
Not possible. You decide between tabs (1 only), or spaces (and specify the number of spaces you want).

**Comment by basickarl** [comment]
@buzinas Alright thanks!

**Comment by jmlopez-rod** [comment]
@basickarl the examples you gave point to the rule provided by tslint. To use the one provided by this project you need to use `"ter-indent"`, see https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/terIndentRule.md
