### ISSUE TITLE
Eslint `curly` rule is not properly supported in tslint

### ISSUE THREAD

**Issue by guidojo** [buzinas/tslint-eslint-rules#205]
Tslint doesn't support the curly rule as eslint does. Tslint only has the options `true` or `false`.

Tslint: https://palantir.github.io/tslint/rules/curly/
Eslint: http://eslint.org/docs/rules/curly

Can you please create an alias for the eslint version, so I can use options like `multi-line`? :-)

**Comment by guidojo** [comment]
This has been solved in the newest tslint rules :)

**Comment by jkasten2** [comment]
@guidojo Do you mean the `ignore-same-line` and `as-needed` options in `tslint`? 

@buzinas @guidojo `eslint` has `multi-or-nest` which is different then these rules. Can this be applied in some way with this plugin? If not I vote to reopen this issue.

Tried a few iterations of setting `"curly":` with `multi-or-nest` in my `tsconfig.json` without any luck.  

Thanks!
