### ISSUE TITLE
Update TSLint Peer Dependency

### ISSUE THREAD

**Issue by mdurling** [buzinas/tslint-eslint-rules#206]
The current peer dependency causes `npm shrinkwrap` to fail when using [TSLint v5.0.0](https://github.com/palantir/tslint/releases/tag/5.0.0)
```
"peerDependencies": {
    "tslint": "^4.5.0"
  },
```
The new version of TSLint works fine, but `npm shrinkwrap` fails saying a peer dependency is unmet. Perhaps the semver of `>=4.5.0` or something similar would be appropriate.

Please update.

**Comment by buzinas** [comment]
Thanks for opening the issue. Please, feel free to open a PR for that and I'll be glad to merge it and release a new version :)

**Comment by mdurling** [comment]
https://github.com/buzinas/tslint-eslint-rules/pull/207

**Comment by jmlopez-rod** [comment]
[v4.0.0](https://github.com/buzinas/tslint-eslint-rules/releases/tag/v4.0.0) has been released.
