### ISSUE TITLE
object-curly-spacing doesn't support objectsInObjects

### ISSUE THREAD

**Issue by dylanfoster** [buzinas/tslint-eslint-rules#222]
as stated in the [eslint rule](http://eslint.org/docs/rules/object-curly-spacing)

**Comment by buzinas** [comment]
It was probably added after we wrote ours. Thanks for the issue!

**Comment by dylanfoster** [comment]
fwiw @buzinas it's not accepting either `objectsInObjects` or `arraysInObjects`

**Comment by jmlopez-rod** [comment]
It should now thanks to @peterjwest (https://github.com/buzinas/tslint-eslint-rules/commit/24190b7059b8c947d7df5b731434566fdd6b5468)
