### ISSUE TITLE
tslint.json rules require Array type[true], [false] instead of true, false

### ISSUE THREAD

**Issue by jogit82** [buzinas/tslint-eslint-rules#224]
I am not sure if this is considered an issue. But I will go ahead and make a pull request after fixing this.        
$ tslint Version 5.2.0
$ tsc Version 2.3.2

This is an "issue" in tslint.json file. I downloaded the tslint.json file from this repo.  I am using vscode which does not like it (green squiggly line) when **"no-consecutive-blank-lines": true**, when I hovered over, tooltip: "Incorrect type: expected Array. Green squiggly line goes away when I give an Array type: **"no-consecutive-blank-lines": [true]**
These are the rules which are currently having the same "issue"
**- "no-consecutive-blank-lines": [true]**
**- "no-inferrable-types": [false]** #223

**Comment by jmlopez-rod** [comment]
I guess your IDE checks the json file and it expects the parameters to be in an array. Does this happen with any of the rules provided by the project? The rule still works as is but I don't see any harm in declaring them as array: https://palantir.github.io/tslint/rules/no-consecutive-blank-lines/

**Comment by jmlopez-rod** [comment]
#223
