### ISSUE TITLE
Recommended preset

### ISSUE THREAD

**Issue by mad-gooze** [buzinas/tslint-eslint-rules#229]
Does this packages have a preset with recommended rules like `tslint:recommended`?

**Comment by buzinas** [comment]
Not at the moment

**Comment by lukecwilliams** [comment]
This would be a nice add for our team - we want to do another pass at improving our linting but activating each rule individually is a bit time-consuming.

**Comment by jmlopez-rod** [comment]
This has been discussed before, since a preset is opinionated this would cause many issues being open arguing about how to best set the configuration. I think this type of configurations should be left to another project, take https://github.com/blakeembrey/tslint-config-standard for instance.

**Comment by lukecwilliams** [comment]
@jmlopez-rod Thanks for the thoughts - we'll look over that repo!

**Comment by buzinas** [comment]
Closing since we don't plan to have this.

**Comment by astorije** [comment]
I know I'm late to the party, but it would be nice to have a recommended preset that enables the same rules as the ones in ESLint's recommended preset.

**Comment by pelotom** [comment]
It seems like the work is already being done to determine which rules are recommended (they are marked as "(Recommended)" in the README), so why not just publish this as a preset? Currently it's a very laborious process to actually write out the rules you want to use, going through the README one by one and transcribing to your `tslint.json`.

**Comment by ryami333** [comment]
Totally agree with @pelotom - the cognitive work here is already done, publishing a recommended preset is the easy bit. Would you not accept a PR? @buzinas?
