### ISSUE TITLE
valid-jsdoc - New option checkparamexistence

### ISSUE THREAD

**Issue by FDiskas** [buzinas/tslint-eslint-rules#233]
For typescript valid-jsdoc is used almost for http://typedoc.org 
> Therefore you don’t have to include additional metadata within your comments, TypeScript specific elements like classes, enumerations or property types and access modifiers will be automatically detected.

So it would be nice to have an option to turn of param checking completely like id done here http://jscs.info/rule/jsDoc#checkparamexistence

Thanks

**Comment by buzinas** [comment]
I know that this rule should probably be different for TypeScript, but since this project aims to mirror the ESLint rules, it wouldn't make sense to change its configuration for that.

**Comment by FDiskas** [comment]
To bad. This is the main issue for us. We are forced to remove that from our project
