### ISSUE TITLE
object-curly-spacing throws error with tslint@4.4.2

### ISSUE THREAD

**Issue by maciejmatu** [buzinas/tslint-eslint-rules#235]
```
TypeError: Lint.Replacement.appendText is not a function
    at ObjectCurlySpacingWalker.checkSpacingInsideBraces (*path*/node_modules/tslint-eslint-rules/dist/rules/objectCurlySpacingRule.js:5
7:44)
```

Current Lint.Replacement method usage from [tslint documentation](https://palantir.github.io/tslint/develop/custom-rules/):
`const replacement = new Lint.Replacement(node.getStart(), node.getWidth(), "");`

**Comment by buzinas** [comment]
Since v4.0.0 ([see CHANGELOG](https://github.com/buzinas/tslint-eslint-rules/blob/master/CHANGELOG.md)), this project is compatible with TSLint 5.x only.

You have two options: upgrade TSLint, or downgrade TSLint ESLint Rules to 3.5.1.
