### ISSUE TITLE
import additional rules

### ISSUE THREAD

**Issue by domoritz** [buzinas/tslint-eslint-rules#236]
Is there a way to import additional rules? For example https://github.com/benmosher/eslint-plugin-import.

**Comment by buzinas** [comment]
I'm not aware of this plugin, can you elaborate, please?

**Comment by domoritz** [comment]
https://github.com/benmosher/eslint-plugin-import is a plugin that adds some additional rules to eslint. I would like to use some rules from there in my typescript project with tslint.

**Comment by buzinas** [comment]
In fact, since our rules are rewrites of ESLint rules to work with the TSLint AST, you can't use ESLint rules at all. The goal of this project is exactly provide some of the rules that exist on ESLint repository that TSLint doesn't have an equivalent.

**Comment by domoritz** [comment]
That makes sense. The only rule I actually want is https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/newline-after-import.md.

**Comment by buzinas** [comment]
That's [probably a very simple rule to write](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/newline-after-import.js).

If you are willing to, you can get my project as a base and create this custom rule.

**Comment by jmlopez-rod** [comment]
See https://github.com/buzinas/tslint-eslint-rules/blob/master/CONTRIBUTING.md for more info on how to start writing the rule if you are willing to.

**Comment by buzinas** [comment]
Closing for now, will re-open in the case you decide to build it.
