### ISSUE TITLE
question: use existing set of eslint's from other modules

### ISSUE THREAD

**Issue by ciekawy** [buzinas/tslint-eslint-rules#248]
in a first TS project within existing custom multi-module JS environment I'd like to reuse existing modules and it's eslint's rules. Usual JS generated project would use sth like
```json
{
  "extends": [
    "@custom/eslint-config",
    "@custom/eslint-config/node6",
    "@custom/eslint-config/es6",
    "@custom/eslint-config/react"
  ]}
```

As this is experimental TS project I'd like to reuse as much as possible from above eslint rules without manually converting them. I've started with the approach:
``` json
{
  "extends": [
    "tslint-eslint-rules",
    "@homeaway/eslint-config",
    "@homeaway/eslint-config/node6",
    "@homeaway/eslint-config/es6",
    "@homeaway/eslint-config/react"
  ],
  "rules": {
    "no-constant-condition": true
  }}
```

Lot of the rules are just not supported and this is clear to me as this is what documentation states. Wonder if there is a way  to just ignore not supported rules and also possibly define others that could be missing and are important in the existing stack.

**Comment by buzinas** [comment]
As far as my knowledge goes, I don't think that's possible :(
