### ISSUE TITLE
About writing new TSLint rules

### ISSUE THREAD

**Issue by trivikr** [buzinas/tslint-eslint-rules#251]
Hi,

First of all, thank you for creating and maintaining tslint-eslint-rules!
Some of our projects use TSLint, and we would like to write new TSLint rules mentioned in [Best Practices](https://github.com/buzinas/tslint-eslint-rules#best-practices) as part of a Hackathon.

Questions:
- Is there a prioritized list of which ESLint rules are important ones to have the TSLint counterparts?
- If anyone is working on existing ESLint rules, can I view the progress somewhere other than the [pull requests](https://github.com/buzinas/tslint-eslint-rules/pulls)
- Should we create issues with labels (say [new rule](https://github.com/buzinas/tslint-eslint-rules/labels/new%20rule)) for each rule we'll work on? Like [this example](https://github.com/buzinas/tslint-eslint-rules/issues/126)

We'll follow the [Contributing Guidelines](https://github.com/buzinas/tslint-eslint-rules/blob/master/CONTRIBUTING.md)

Regards,
Trivikram

**Comment by buzinas** [comment]
Hey Trivikram, thanks for your message!

I'll be very thankful for your help on this :)
Here are your answers:

> Is there a prioritized list of which ESLint rules are important ones to have the TSLint counterparts?

I don't think so, you can prioritize as your judgement.

> If anyone is working on existing ESLint rules, can I view the progress somewhere other than the pull requests

Ideally, we should have opened issues and people can comment/tag themselves if they start working on it.

> Should we create issues with labels (say new rule) for each rule we'll work on? Like this example
Hell yea!

**Comment by trivikr** [comment]
Thanks @buzinas !
I'll check with my friends and select one day to contribute to this project. As of now, we're busy till 09/30

While working on a new rule:
- We'll create an issue with [new rule](https://github.com/buzinas/tslint-eslint-rules/labels/new%20rule) to track the work
- We'll follow the [Contributing Guidelines](https://github.com/buzinas/tslint-eslint-rules/blob/master/CONTRIBUTING.md) and post a PR :-)

This issue can be resolved.
