### ISSUE TITLE
Partial implementation of ESLint rule?

### ISSUE THREAD

**Issue by Izhaki** [buzinas/tslint-eslint-rules#259]
When it comes to the `semi` rule, TSLint is missing the [`omitLastInOneLineBlock`](https://eslint.org/docs/rules/semi) rule that ESLint implements.

Yet in the chart the `semi` rule is marked as "provided natively".

Just wonder if "provided natively" is a mistake, or that partial implementation is considered as full one?

**Comment by buzinas** [comment]
Probably we should update the docs to show it as partially provided natively.
