### ISSUE TITLE
improvement "sort-imports" : grouping + newlinebetween

### ISSUE THREAD

**Issue by wesleymostien** [buzinas/tslint-eslint-rules#264]
like on https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

- ability to group member types (and considerate 1 group) 
- also force a newline between each group

**Comment by buzinas** [comment]
Hey Wesley, thanks for the suggestion!

Although I appreciate the rule, it's out of scope of this project (which is to have core ESLint rules mirrored for TSLint). I recommend that you fork this project, remove all the current rules and create any rules you think it's valuable for the community and publish your own package to npm :)
