### ISSUE TITLE
Rules cannot be set to warning

### ISSUE THREAD

**Issue by jez9999** [buzinas/tslint-eslint-rules#265]
For some reason these rules don't work with the normal TSLint syntax, for example this should set the indent rule to warning:

    "rules": {
		"ter-indent": {
			"severity": "warning",
			"options": ["tab", {"SwitchCase": 1}]
		},

... but it still gives me an error when the rule is violated.

**Comment by buzinas** [comment]
@jmlopez-rod can you take a look at this one?

**Comment by jez9999** [comment]
I must've been doing something wrong, it's working now.
