### ISSUE TITLE
Release master to support TS 2.6

### ISSUE THREAD

**Issue by zakjan** [buzinas/tslint-eslint-rules#273]
Please release a new version, because the latest tag 4.1.1 depends on tsutils@^1.4.0, while master depends on ^2.4.0. tsutils@^1.4.0 can't be used with TS 2.6.

**Comment by buzinas** [comment]
I'll release as soon as I check/merge the pending PRs. Sorry for the delay!

**Comment by reduckted** [comment]
Any update on this? I'm hanging out for #238 to be released. Is there anything we can do to help?

**Comment by LandonSchropp** [comment]
I'd also really appreciate an update. I just spent an hour trying to figure out why my custom `tslint-eslint-rules` weren't being applied before I ran across this issue.

**Comment by buzinas** [comment]
Hopefully by Dec 7th!

**Comment by johan** [comment]
Any update on this? The https://github.com/buzinas/tslint-eslint-rules/compare/v4.1.0...master history comparison shows it's been a long while. Is there additional peer review or similar happening between landing PR:s and new package versions getting published to npm?

**Comment by taylon** [comment]
@buzinas anything we can do to help here?

**Comment by buzinas** [comment]
Latest master was released, thanks!
