### ISSUE TITLE
About using Prettier in tslint-eslint-rules

### ISSUE THREAD

**Issue by trivikr** [buzinas/tslint-eslint-rules#280]
Can we use [Prettier](https://github.com/prettier/prettier) for formatting TypeScript code in tslint-eslint-rules?
Prettier is an opinionated code formatter. It removes all original styling and ensures that all outputted code conforms to a consistent style.

We recently started using Prettier for private projects, and life has been better. We don't worry/argue about formatting any more 😊
Of course there was initial oppositions to some of the decisions taken by Prettier (like [lack of parenthesis around single param arrow functions](https://github.com/prettier/prettier/issues/812)), but we got used to it with time. [**Update**: [Prettier 1.9](https://github.com/prettier/prettier/releases/tag/1.9.0) now has support for arrowParens]
For Open Source projects which don't use Prettier, I manually run Prettier CLI for the files which I'm editing. I believe developers will be more productive if we use formatters like Prettier in tslint-eslint-rules. What do you think?

**Comment by buzinas** [comment]
Sure thing! I love Prettier :)

**Comment by trivikr** [comment]
👍
I'll raise a PR with Prettier once my other PRs are merged to master https://github.com/buzinas/tslint-eslint-rules/pulls

**Comment by jmlopez-rod** [comment]
FYI, we do lint our code in an opinionated way using the rules we create: https://github.com/buzinas/tslint-eslint-rules/blob/master/tslint_eslint_rules.json

This is ran everytime we use `npm test` as well as the rules from `tslint.json`.

**Comment by trivikr** [comment]
Sure, I'll remove tslint-eslint-rules used in this project which are conflicting with Prettier formatting rules.

**Comment by trivikr** [comment]
Closing as TSLint is going to deprecated some time in 2019 ([announcement](https://github.com/palantir/tslint/issues/4534))
