### ISSUE TITLE
Tslint in tsx with tabs implemented with space.

### ISSUE THREAD

**Issue by sumanTitan** [buzinas/tslint-eslint-rules#286]
I have my configuration set as:
`"ter-max-len": [
            true,
            100,
            {
                "tabWidth": 4,
                "ignoreUrls": true,
                "ignoreStrings": true,
                "ignoreComments": true
            }
        ]`

Now when I indent my jsx and reaches more than 100 characters, tslint shows error.

The issue is I have jsx indented 10 times or more so 40 characters are taken by the indentation.
Is there a way to ignore those indentation i have

**Comment by buzinas** [comment]
Not really. The `max-len` rule goal is to make the code horizontally readable, to fit multiple tabs open side by side etc. By ignoring the indentation, the rule loses its purpose.

Unrelated, but I'd suggest you to decrease your `tabWidth` to `2`, and you'll be able to see much more code, while still having a nice readable code.
