### ISSUE TITLE
got error under tslint v5.9.1

### ISSUE THREAD

**Issue by waitingsong** [buzinas/tslint-eslint-rules#287]
> $ tslint --version
> 5.9.1
> $ tsc --version
> Version 2.6.2

"tslint-eslint-rules": "^4.1.1"

I run lint ```tslint -p tslint.json src/**/*.ts test/**/*.ts``` , then got error under tslint **v.5.9.1** , but no error under tslint **v5.8.0**
> **error TS5024: Compiler option 'extends' requires a value of type string.**

- tslint.json
```
{
  "extends": [
    "tslint-eslint-rules"
  ],
  "rules": {
    "triple-equals": true
  },
  "rulesDirectory": [
    "node_modules/tslint-eslint-rules/dist/rules"
  ]
}
```

Also error if i use below:
```
{
  "extends": [
    "tslint-eslint-rules"
  ],
  "rules": {
    "triple-equals": true
  }
}
```

It's work no error:
```
{
  "rules": {
    "triple-equals": true
  },
  "rulesDirectory": [
    "node_modules/tslint-eslint-rules/dist/rules"
  ]
}
```

The reason of using both extends and rulesDirectory is i want to use it in angular project:
```
{
  "extends": [
    "tslint-eslint-rules"
  ],
  "rules": {
    "triple-equals": true
    // ....
  },
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
}
```

or should i post this to the issues of tslint?

**Comment by buzinas** [comment]
Latest master was released, which supports TS v5.x.x
