### ISSUE TITLE
Switch to yarn

### ISSUE THREAD

**Issue by jmlopez-rod** [buzinas/tslint-eslint-rules#292]
I think its time to get the builds in order. @buzinas suggested to switch to yarn so that we can avoid failed builds because npm obtained a different package from the one in our machines.

I'm also noticing that we have a typings folder. I think most of them can be replaced by installing from `@types`.

Also, since there will be more collaborators with permissions to merge and publish it would be good to update the CONTRIBUTING.md file.

**Comment by jmlopez-rod** [comment]
@buzinas npm just released a "better" npm with the `ci` command? should we try it before we jump into the yarn train?

**Comment by buzinas** [comment]
@jmlopez-rod I've been using yarn over the last 13 months and to be honest, I never looked back

**Comment by jmlopez-rod** [comment]
That's right, we are using yarn now!
