### ISSUE TITLE
how to enable all recommended rules?

### ISSUE THREAD

**Issue by meritozh** [buzinas/tslint-eslint-rules#293]
I don't want add all recommended rules one by one manually. Can it support `tslint-eslint-rules:recommended` in *tslint.json* `extends` field?

**Comment by jmlopez-rod** [comment]
The "recomended" text comes from eslint. Even if it is recommended the options that someone would put in there might not be the ones that you want. This project is not meant to create the configuration for you. You have to look at other projects that provide you with a configuration file such as https://github.com/blakeembrey/tslint-config-standard

The goal of this project is solely to provide the rules. If we start creating a configuration file we'll end up doing the job of https://github.com/airbnb/javascript with lots of issues and PRs asking to change a configuration to meet their needs.
