### ISSUE TITLE
can we have any rule for checking the annotations on the function

### ISSUE THREAD

**Issue by RaneAshwini** [buzinas/tslint-eslint-rules#337]
I have code like
@check()
public checkFun()
{
// code
}
How do I add the rule to check functions should have @check() annotation everytime some one add new function.

**Comment by jmlopez-rod** [comment]
I'm not sure if one exists. This is certainly possible but I think this is outside the scope of the project. We only try add eslint rules that are not currently supported by tslint.

If you want to write your own custom rule and you have no idea where to start I would look at any rule that deals with annotations. I don't think I've seen one in this project but I think the angular team uses the codelyzer rules which may give you a bit of an insight as to how to go about writing one.

https://github.com/mgechev/codelyzer
