### ISSUE TITLE
Update dependency for typescript@3.0.0

### ISSUE THREAD

**Issue by a88zach** [buzinas/tslint-eslint-rules#344]
tsutils@2.8.0 is not compatible with typescript@3.0.0 and above.  The issue was fixed in tsutils@2.27.2

https://github.com/ajafff/tsutils/pull/66

please update tsutils to a version compatible with typescript@3.0.0

**Comment by alecf** [comment]
@buzinas ping..

**Comment by jmlopez-rod** [comment]
I updated the project to use typescript > 3.0 and updated tsutils as well:

https://github.com/buzinas/tslint-eslint-rules/pull/345

**Comment by jmlopez-rod** [comment]
To be released shortly
