### ISSUE TITLE
Can ESLint plugins be used through this dependency?

### ISSUE THREAD

**Issue by telmotrooper** [buzinas/tslint-eslint-rules#357]
I already use `tslint-eslint-rules` in my project, but right now I'm trying to use the import rules from `eslint-plugin-import` as well with no success.

I'd like to know if this extension allows me to use ESLint plugins as well in my TypeScript project.

Attempting to extend `plugin:import/warnings` gives me an error.
```
Failed to load /home/telmo/Development/getPDV/tslint.json: Invalid "extends" configuration value - could not require "plugin:import/warnings". Revie
w the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced
 configuration file.
```
 And just setting the rule `"import/order": ["error", {"groups": ["index", "sibling", "parent", "internal", "external", "builtin"]}]` is just plain ignored.

Should I be asking this in `eslint-plugin-import`'s repository?

**Comment by wolfy1339** [comment]
No, this is only the builtin ruleset from eslint. It does not allow plugins to be imported
