### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by hvaara** [buzinas/tslint-eslint-rules#378]
Are you planning a new release of this plugin soon? We would really love to see #353 in the released version.

Thanks a lot for this project by the way! Very helpful! 🎉

**Comment by buzinas** [comment]
To be honest, I really need help from other maintainers. It's been hard to find time to re-organize this project and put it into the right direction. I'm really sorry :(

**Comment by hvaara** [comment]
Ok. Thanks for getting back to me so quick, and also thanks once again for the great work! I'll close this issue
