### ISSUE TITLE
Soon: May use extends

### ISSUE THREAD

**Issue by unional** [buzinas/tslint-eslint-rules#53]
https://github.com/palantir/tslint/pull/1016#issuecomment-194076774
With the `extends` feature, custom rules could be published as `tslint-config-X` too. Rules directory will be merged.:
```js
// tslint-eslint-rules -> tslint-config-eslint
// main: tslint.json
{
  "rulesDirectory": "./<local rule relative path>",
  "rules": {
    // Can add default rules value here, and
    // disable conflicting core rules if needed.
  } 
}
```
:smile:

**Comment by buzinas** [comment]
Can you explain how it affects this library, please?

**Comment by unional** [comment]
Currently I'm discussing with @JKillian about how to handle `rulesDirectory`.
See this comment: https://github.com/palantir/tslint/pull/1016#issuecomment-194690545
The issue is the relative path through `node_modules` as it is different between npm 2/3+.

My opinion is that consumer should not reference things in `node_modules` directly as in your example in README

```js
{
  "rulesDirectory": "node_modules/tslint-eslint-rules/dist/rules"
}
```

If use the `extends` feature, then it can be a local path, i.e.:
https://github.com/palantir/tslint/pull/1016#issuecomment-194686772

Right now I'm waiting for https://github.com/palantir/tslint/pull/1035 to goes in so I can refactor the code.  Please feel free to join the discussion. :beer:

**Comment by buzinas** [comment]
Can't your project be a peer dependency to mine, instead of a true dependency?

**Comment by unional** [comment]
If it is a peer dependency, that means the user need to aware of using `tslint-eslint-rules` and also do the `rulesDirectory: "node_modules/tslint-eslint-rules/dist/rules"` themselves in order for it to work.

i.e., the user need to:
```sh
npm i tslint tslint-config-unional tslint-eslint-rules
```
```js
{
  "extends": "tslint-config-unional",
  "rulesDirectory": "node_modules/tslint-eslint-rules/dist/rules"
}
```

instead of:
```sh
npm i tslint tslint-config-unional
```
```js
{
  "extends": "tslint-config-unional"
}
```

**Comment by buzinas** [comment]
Merged https://github.com/buzinas/tslint-eslint-rules/pull/59, and hopefully @JKillian will be handling that inside TSLint.

**Comment by unional** [comment]
`extends` has landed. Now your user can reference your package through:
```js
{
  "extends": "tslint-eslint-rules"
}
```
What you need is in your own `tslint.json`:
```js
{
  "rulesDirectory": "./dist/rules"
}
```

Cheers,
Unional

:rose:

**Comment by buzinas** [comment]
Thanks, @unional! Good job :)

**Comment by JKillian** [comment]
Just to follow up on this, might be worth making this small tweak! It shouldn't break anything for users who are using your package in other ways, but will let new users use `extends` if they want to. @unional want to make a PR for this?

**Comment by unional** [comment]
I'm busy until end of next week. Can do it by then if it is not done sooner. :)
