### ISSUE TITLE
Create array-bracket-spacing rule

### ISSUE THREAD

**Issue by buzinas** [buzinas/tslint-eslint-rules#57]
We're gonna need this to our projects, and tslint can also benefits from this (https://github.com/palantir/tslint/issues/1045.).

**Comment by nfriend** [comment]
This might be relevant while you work on this rule:

https://github.com/eslint/eslint/issues/5768

**Comment by buzinas** [comment]
@nfriend I told you that I had started this rule, but it was a mistake. I started [object-curly-spacing](https://github.com/buzinas/tslint-eslint-rules/issues/58) (somewhat similar to this one) with my friend.

Feel free to take this one for you, if you want to :)

**Comment by nfriend** [comment]
Awesome, I'll keep working on it.

**Comment by buzinas** [comment]
Whoa, that's awesome! Thanks very much :smile:

**Comment by buzinas** [comment]
@nfriend Version 1.2.0 released, thanks!
