### ISSUE TITLE
Create object-curly-spacing rule

### ISSUE THREAD

**Issue by buzinas** [buzinas/tslint-eslint-rules#58]
We're gonna need this for our projects, and tslint can also benefits from this (https://github.com/palantir/tslint/issues/1044).

**Comment by jkyoutsey** [comment]
Road map? ETA?

**Comment by buzinas** [comment]
Unfortunately, no ETA, too busy lately, and I can't estimate when this is gonna end.

But please, feel free to open a PR for it, if you want to.

**Comment by Hufschmidt** [comment]
Please merge the PR. The current behaviour makes the _block-spacing_ rule pretty useless in its current state. :(

**Comment by buzinas** [comment]
@jkyoutsey It will be available in v1.5.0

**Comment by buzinas** [comment]
Version 1.5.0 released!
