### ISSUE TITLE
Create array-bracket-spacing rule

### ISSUE THREAD

**Issue by nfriend** [buzinas/tslint-eslint-rules#68]

**Comment by nfriend** [comment]
I have a good start on this rule.  Just need to figure out some edge cases.

**Comment by buzinas** [comment]
@nfriend There is already an opened issue for this: https://github.com/buzinas/tslint-eslint-rules/issues/57

Btw, I have already started it, so, you maybe should choose another one :P

**Comment by nfriend** [comment]
Whoops, guess I should have searched through the other issues first :)

**Comment by buzinas** [comment]
@nfriend If possible, could you please put an example of this rule in https://github.com/buzinas/tslint-eslint-rules/blob/master/eslint_tslint.json and update README, please?

**Comment by buzinas** [comment]
Forgot to ask during the Pull Request.

**Comment by nfriend** [comment]
@buzinas Sure, no problem.

**Comment by nfriend** [comment]
See #70.
