### ISSUE TITLE
Create camelcase rule

### ISSUE THREAD

**Issue by nfriend** [buzinas/tslint-eslint-rules#78]
http://eslint.org/docs/rules/camelcase

**Comment by buzinas** [comment]
I think we have `variable-name` for that in TSLint, don't we?

**Comment by nfriend** [comment]
Yes, you're right.  Good catch.

**Comment by vort3xxx** [comment]
The behavior seems a little different.  It's picking up functional parameters (dependency injections especially) and consts in the tslint rule.  I don't believe that eslint had that scoping.  It seemed to only inspect var and let statements.
