### ISSUE TITLE
Best way to use latest code out of git on a project?

### ISSUE THREAD

**Issue by abierbaum** [buzinas/tslint-eslint-rules#83]
I have been using tslint-eslint-rules for a few weeks.  It is a great project and is proving very helpful.

We are currently using it by pulling it in as a devDependency using npm.  It all works great.

I noticed that there are some new rules that have been added but there is no new release available.  I am trying to find a way to use the latest master HEAD but can't find an easy way to do this.

I tried using the following package specification to pull it directly from github.

```
"tslint-eslint-rules": "buzinas/tslint-eslint-rules#9f575",
```

This pulls from the project, but only pulls the following files:

```
CHANGELOG.md
index.js
LICENSE
package.json
README.md 
```

So it doesn't have the `dist/rules` directory.  

Is there some other way I am missing to make use of the latest and greatest version?

**Comment by buzinas** [comment]
Hi, @abierbaum. Thanks for the issue!

Currently, only the NPM packages have the compiled rules, so you won't be able to use directly from Github.

If you really want to use the latest and greatest before a version is published, you can clone this repo, and then run `npm i`. After everything is installed, you should run `gulp build`.
After that, you'll have the rules compiled into `dist/rules` and you can use them.

Although, I recommend to open an issue here when that's needed, and I can easily publish a new version for you. And that's exactly what I'll be doing now.

**Comment by buzinas** [comment]
New version published to NPM :)
