### ISSUE TITLE
no-extra-boolean-cast misses double negation when certain operators are present 

### ISSUE THREAD

**Issue by ksiegel** [buzinas/tslint-eslint-rules#87]
The following two don't fail:
`if (!!lastUpdated && !!savedJwt) {` 
`if (!!lastUpdated || !!savedJwt) {`

I don't know the TS lib well enough to submit a PR, but I think the logic here should change:
https://github.com/buzinas/tslint-eslint-rules/blob/master/src/rules/noExtraBooleanCastRule.ts#L33

Thanks for everything - great library!

**Comment by buzinas** [comment]
The issue was fixed and the problem won't happen anymore in the next release.

**Comment by buzinas** [comment]
@ksiegel v1.6.0 released
