### ISSUE TITLE
no-constant-condition doesn't consider checkLoops

### ISSUE THREAD

**Issue by ova2** [buzinas/tslint-eslint-rules#92]
There is a new boolean option `checkLoops` which is very useful. See http://eslint.org/docs/rules/no-constant-condition

But it is impossible to configure it because the current rule for `no-constant-condition` doesn't consider this option. I want to configure this rule as follows:

```
no-constant-condition: [true, {"checkLoops": false}]
```

**Comment by buzinas** [comment]
Thanks for the issue. I would be glad to accept a PR for this.

**Comment by buzinas** [comment]
The option was added and it will be available in the next release.

**Comment by buzinas** [comment]
@ova2 v1.6.0 released

**Comment by ova2** [comment]
Thanks. Amazing. I will check it.
