### ISSUE TITLE
Usage in VSCode?

### ISSUE THREAD

**Issue by bcherny** [buzinas/tslint-eslint-rules#95]

**Comment by buzinas** [comment]
You must install the [TSLint extension](https://github.com/Microsoft/vscode-tslint) and then, in your `tslint.json` file, you must configure a `rulesDirectory` property, e.g:

```json
{
    "rulesDirectory": "node_modules/tslint-eslint-rules/dist/rules",
    "rules": {
      "no-constant-condition": true
    }
  }
```

**Comment by bcherny** [comment]
That's what I tried, and it doesn't seem to work. As soon as I add the `object-shorthand` line to my tslint.json, the tslint service crashes silently so linting stops working (due to https://github.com/Microsoft/vscode-tslint/issues/66).

Is there another place I should put my eslint rules, instead of mixing them into my tslint rules?

tslint.json:

```json
{
  "rules": {
    "semicolon": [true, "never"],
    "object-shorthand": ["properties"]
  },
  "rulesDirectory": "./node_modules/tslint-eslint-rules/dist/rules"
}
```

**Comment by buzinas** [comment]
That's because `object-shorthand` is a rule that we didn't port from ESLint to TSLint ESLint Rules yet.

In [our README](https://github.com/buzinas/tslint-eslint-rules/blob/master/README.md), you can see all the rules and their current status. If a rule has the word "TODO" right besides it, it means that this rule wasn't ported yet.

**Comment by bcherny** [comment]
Ah, got it. The first few rules in the readme don't have TODOs, so I assumed all the rules are supported.

At a high level it seems like a bad idea to manually port eslint rules, as they're a fast moving target. A loftier goal might be an AST transformer that takes a TypeScript AST and gives an Esprima-compatible AST, so it can be passed to eslint as a parser.

Anyway, thanks for helping debug!
