### ISSUE TITLE
Comma dandle rule

### ISSUE THREAD

**Issue by eduardonunesp** [buzinas/tslint-eslint-rules#96]
The comma-dangle rule is present on the tslint documentation, but isn't available on rules

**Comment by buzinas** [comment]
There is a similar rule already available in TSLint. You can see in the README:

comma-dangle (ESLint) => trailing-comma (TSLint)

    "trailing-comma": [
      true,
      {
        "multiline": "never",
        "singleline": "never"
      }
    ]
